global:
  checkNewVersion: false
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: '80'
    # http:
    #   redirections:
    #     entryPoint:
    #       to: websecure

  websecure:
    address: '443'
    # http:
    #   middlewares:
    #     secureHeaders:
    #       headers:
    #         forceSTSHeader: true
    #         stsIncludeSubdomains: true
    #         stsPreload: true
    #         stsSeconds: 31536000
    #   tls:
    #     certResolver: letsencrypt

# providers:
#   docker:
#     endpoint: unix:///var/run/docker.sock
#     watch: true
#     exposedByDefault: false

# certificatesResolvers:
#   letsencrypt:
#     acme:
#       email: "aravindr597@gmail.com"
#       storage: acme.json
#       keyType: 'EC256'
#       certificatesDuration: 2160
#       httpChallenge:
#         entryPoint: web
