- name: Detect WSL
  ansible.builtin.shell: |
    echo $(cat /proc/version | awk '{ if ($0 ~ /WSL/ && $0 ~ /microsoft/) print "true"; else print "false"; }')
  register: ansible_host_environment_is_wsl
  args:
    executable: /bin/bash
  ignore_errors: true
  changed_when: false


- name: Register WSL State fact
  ansible.builtin.set_fact:
    ansible_host_environment_is_wsl: "{{ ansible_host_environment_is_wsl.stdout }}"

- name: Print WSL State
  ansible.builtin.debug:
    msg: "WSL State: '{{ ansible_host_environment_is_wsl }}'"
