- name: Neovim | install neovim
  package:
    name: neovim
    state: present

- block:
  - name: Neovim | find the folders inside nvim dir
    file:
      src: "{{playbook_dir}}/files/nvim/"
      dest: "{{ansible_user_dir}}/.config/nvim/"
      state: link
    when: dry_run is false
